application/authentication/urls.py
from collections import namedtuple
from django.conf.urls import url
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views, forms

app_name = 'authentication'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html',
                                                authentication_form=forms.CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='authentication/logout.html'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('account/', views.ConsultAccountView.as_view(), name='account'),
    path('register/confirmation', views.ConfirmationView.as_view(), name='confirmation'),
    path('register/validation/<str:uid>/<str:utoken>', views.ValidationView.as_view(), name='validation'),
    path('register/success', views.SuccessView.as_view(), name='success'),
    path('account/change-password', auth_views.PasswordChangeView.as_view(template_name='authentication/change-password.html',
                                                                          success_url='password-changed'), name='change-password'),
    path('account/password-changed', auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password-changed.html'), name='password-changed'),
    path('login/reset', auth_views.PasswordResetView.as_view(template_name='authentication/password_reset_1.html',
                                                             email_template_name='authentication/password_reset_email.html',
                                                             subject_template_name='authentication/password_reset_subject.txt',
                                                             success_url='reset_confirmed'), name='forgotten-password'),
    path('login/reset_confirmed', auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_2.html'), name='reset_confirmed'),
    path('login/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_3.html',
                                                                                     success_url=reverse_lazy('authentication:password_reset_complete')), name='password_reset_confirm'),
    path('login/reset/confirmed', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_4.html'), name='password_reset_complete'),
]

application/bookmark/urls.py
from django.urls import path
from . import views

app_name = 'bookmark'

urlpatterns = [
    path('consult/', views.BookmarksView.as_view(), name='consult'),
    path('add/', views.AddBookmarkView.as_view(), name='add-bookmark'),
    # path('check/', views.CheckBookmarkView.as_view(), name='check-bookmark'),
]

application/main/urls.py
from django.urls.conf import path, re_path
from .views import HomeView, ProductView, ResultsView, MentionsView, CategoriesView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('mentionslegales/', MentionsView.as_view(), name='mentions'),
    # path('list/', ProductListView.as_view(), name='product-list'),
    path('results/', ResultsView.as_view(), name='results'),
    path('product/<int:pk>', ProductView.as_view(), name='product_detail'),
    path('categories/', CategoriesView.as_view(), name='categories'),
]

pur_beurre/urls.py
from django.contrib import admin
from django.conf.urls import handler404, url
from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('application.main.urls'), name="home"),
    url('admin/', admin.site.urls),
    url('user/', include('application.authentication.urls'), name="user"),
    url('bookmark/', include('application.bookmark.urls'), name='bookmarks'),
]

handler404 = 'pur_beurre.views.handler404_view'

application/main/models.py
import pprint
from django.db import models
from django.db.models.aggregates import Max
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.contrib.postgres.search import SearchVector


# Create your models here.
class Store(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return 'store: ' + self.name


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return 'category: ' + self.name


class Product(models.Model):
    """
    Class defining the model of the Product object and its methods.
    """
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    nutriscore = models.CharField(max_length=1)
    description = models.TextField()
    url = models.CharField(max_length=200)
    store = models.ManyToManyField(Store)
    popularity = models.IntegerField()
    category = models.ManyToManyField(Category)
    salt = models.CharField(max_length=10)
    sugars = models.CharField(max_length=10)
    saturated = models.CharField(max_length=10)
    fat = models.CharField(max_length=10)
    image_url = models.CharField(max_length=100)
    small_image_url = models.CharField(max_length=100)

    def __str__(self) -> str:
        return 'product: ' + self.name

    # def retrieve_prod_with_code(code):
    #     """
    #     retrieves a product with its primary key
    #     """
    #     product = Product.objects.get(code=code)
    #     return product

    def retrieve_prod_with_pk(pk):
        """
        retrieves a product with its primary key
        """
        product = Product.objects.get(pk=pk)
        return product

    def retrieve_product(request):
        """
        Function used to retrieve the product matching the best with the user request.
        """
        scores = {}
        user_request = request.replace('-', ' ')
        nb_words_request = len(user_request.split(' '))
        products = Product.objects.annotate(search=SearchVector('name')).filter(search=user_request)
        if products:
            for product in products:
                score, score_2 = 0, 0
                string_product = product.name.replace('-', ' ').lower().split(' ')
                for word in string_product:
                    score += 1 if word in user_request.lower() else score
                score_final_1 = round((score/nb_words_request) * 100)
                for word in user_request.split(' '):
                    score_2 += 1 if word.lower() in string_product else score_2
                score_final_2 = round((score_2/len(string_product)) * 100)
                score_final_1 = 100 if score_final_1 > 100 else score_final_1
                score_final_2 = 100 if score_final_2 > 100 else score_final_2
                score_final = (score_final_1 + score_final_2) / 2
                if score_final == 100:
                    category = product.category.all()
                    return product, category
                scores[score_final] = product.code
            if scores:
                maxi = 0
                for key in scores:
                    maxi = key if key > maxi else maxi
                winner = Product.objects.get(code=scores[maxi])
                category = product.category.all()
                return winner, category
        else:
            return None, None

    # def retrieve_product_bis(request):
    #     """
    #     Function used to retrieve the product matching the best with the user request.
    #     """
    #     scores = {}
    #     user_request = request.replace('-', ' ')
    #     nb_words_request = len(user_request.split(' '))
    #     products = Product.objects.annotate(search=SearchVector('name')).filter(search=user_request)
    #     if products:
    #         for product in products:
    #             score, score_2 = 0, 0
    #             string_product = product.name.replace('-', ' ').lower().split(' ')
    #             for word in string_product:
    #                 score += 1 if word in user_request.lower() else score
    #             score_final_1 = round((score/nb_words_request) * 100)
    #             for word in user_request.split(' '):
    #                 score_2 += 1 if word.lower() in string_product else score_2
    #             score_final_2 = round((score_2/len(string_product)) * 100)
    #             score_final_1 = 100 if score_final_1 > 100 else score_final_1
    #             score_final_2 = 100 if score_final_2 > 100 else score_final_2
    #             score_final = (score_final_1 + score_final_2) / 2
    #             # if score_final == 100:
    #             #     category = product.category.all()
    #             #     return product, category
    #             scores[score_final] = product.code
    #         if scores:
    #             sorted_scores = sorted(scores, reverse=True)
    #             sorted_scores_dic = {}
    #             for score in sorted_scores:
    #                 sorted_scores_dic[score] = scores[score]
    #             print(sorted_scores_dic)
    #             return sorted_scores_dic
    #             # maxi = 0
    #             # for key in scores:
    #             #     maxi = key if key > maxi else maxi
    #             # winner = Product.objects.get(code=scores[maxi])
    #             # category = product.category.all()
    #             # return winner, category
    #     else:
    #         return None, None

    def generate_suggestions(categories, winner):
        """
        Function formating and generating the chosen suggestions.
        """
        nutri = ['a', 'b', 'c', 'd', 'e']
        pre_suggestions = []
        i = 0
        j = 1
        while len(pre_suggestions) < 6:
            results_raw = Product.objects.filter(category=categories[j].id, nutriscore=nutri[0 + i])
            results_list = [element for element in results_raw]
            results_list.remove(winner.code) if winner.code in results_list else None
            if winner.nutriscore == nutri[0 + i]:
                if i == 0 and j == 0:
                    return 0
                if pre_suggestions != []:
                    suggestions = [Product.objects.get(code=element.code) for element in pre_suggestions]
                    if j == 1:
                        j, i = 0, 0
                    else:
                        return suggestions
                elif pre_suggestions == [] and j == 0:
                    return 0
                elif pre_suggestions == [] and j == 1:
                    j, i = 0, 0
            else:
                for element in results_list:
                    pre_suggestions.append(element)
                i += 1
        suggestions = [Product.objects.get(code=element.code) for element in pre_suggestions[:6]]
        return suggestions


class History(models.Model):
    """
    Class defining the model of the databse feeding history.
    Each time the command manage.py db_feed is called, a history object is created with the OpenFoodFacts request page_number used.
    The first feed ever of the database will look for page 1 when sending a request to OpenFoodFacts.
    The second feed will ask the page 2, the third page 3 etc.
    Each history object also has the date and time of the moment it's completed.
    """
    page_number = models.IntegerField(primary_key=True)
    date = models.DateTimeField(default=timezone.now)

application/main/views.py
import json
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import FormView
from django.views.generic.base import View
from django import forms
from .models import Product
from application.bookmark.models import Substitution


# Create your views here.
class HomeView(FormView):
    """
    View displaying the homepage of the website.
    """
    template_name = 'main/index.html'
    form_class = forms.Form


# class ProductListView(View):
#     """
#     """
#     def get(self, *args):
#         user_input = self.request.GET.get('recherche')
#         products = Product.retrieve_product_bis(user_input)
#         data = {
#             'products': {}
#         }
#         for product in products:
#             result = Product.retrieve_prod_with_code(products[product])
#             data['products'][product] = result.name
#         return JsonResponse(data)


class ResultsView(TemplateView):
    """
    View displaying the results of a user request.
    """
    template_name = 'main/results.html'

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)
        current_user = self.request.user
        user_input = self.request.GET.get('recherche')
        product, category = Product.retrieve_product(user_input)
        if product:
            suggestions = Product.generate_suggestions(category, product)
            user_favs = Substitution.check_favs(product, current_user)
        else:
            suggestions = None
            user_favs = []
        context['user_favs'] = user_favs
        context['product'] = product
        context['suggestions'] = suggestions
        context['category'] = category
        return context


class ProductView(DetailView):
    """
    View displaying the detail page of a product.
    """
    template_name = 'main/product_detail.html'
    model = Product

    def get(self, request, pk):
        product = Product.objects.get(id=pk)
        stores = product.store.all()
        product_stores = [store.name for store in stores]
        return render(request, self.template_name, locals())


class MentionsView(TemplateView):
    """
    View displaying the mentions légales page.
    """
    template_name = 'mentions.html'


class CategoriesView(TemplateView):
    """
    View displaying the categories list page.
    """
    template_name = 'main/categories.html'

    def get(self, request):
        with open('application/main/management/commands/settings.json', 'r') as settings:
            data = json.load(settings)
        categories = data['categories']
        return render(request, self.template_name, locals())

templates/main/categories.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/categories.css' %}">
<div class="section">
    <div class="">
        {% if categories %}
        <h2>Voici les catégories disponibles:</h2>
        <br>
        {% for main, subs in categories.items %}
        <ul>
            <li>
                {{main.title}}
                {% for sub in subs %}
                <ul>
                    <li>{{sub.title}}</li>
                </ul>
                {% endfor %}
            </li>
        </ul>
        {% endfor %}
    </div>
    {% else %}
    <p>Nous ne disposons pas de catégorie pour le moment.</p>
    {% endif %}
</div>

{% endblock %}

templates/main/index.html
{% extends 'base.html' %}

{% block content %}

<!-- Masthead-->
{% load static %}
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-12 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
                <h2 class="text-white font-weight-bold">Trouvez un produit de substitution pour ceux que vous consommez
                    tous les jours.</h2>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-12 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">N'attendez plus, cherchez un produit dans notre base de
                    données et trouver une meilleure alternative !</p>
                <a href="{% url 'categories' %}">
                    <p class="text-white-75 font-weight-light mb-5"><u>Consultez ici les catégories de produits disponibles.</u></p>
                </a>
            {% if user.is_authenticated and perms.main.view_product %}
                <div class="col-md-6 offset-md-3">
                    <form method="get" action="/results/">
                        <input class="form-control" type="text" placeholder="Chercher un produit" name="recherche" required>
                        <br>
                        <button type="submit" class="btn btn-info">Rechercher</button>
                        <ul id="results-list">
                        </ul>
                    </form>
            {% else %}
                    <p class="text-white-75 font-weight-light mb-5">Connectez-vous pour pouvoir effectuer une recherche d'aliment.</p>
                    <a href="{% url 'authentication:register' %}">
                        <p class="text-white-75 font-weight-light mb-5">
                            <u>Si vous n'avez pas encore de compte, cliquez ici pour vous inscrire !</u>
                        </p>
                    </a>
                </div>
            {% endif %}
            </div>
        </div>
    </div>
</header>
<!-- About-->
<section class="page-section bg-primary">
    <div class="container">
        <div class="col-lg-12 text-center">
            <h2 class="mt-0">Colette et Remy</h2>
            <hr class="divider my-4" />
            <p class="text-about">De la ratatouille aux croissants
                Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que
                vous avez déjà
                certainement rencontrés dans notre excellent restaurant Ratatouille.</p>
        </div>
    </div>
    <div class="about">
        <div class="text-about">
            <p><u>Colette Tatou :</u> "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche,
                du bon fromage de
                chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au
                supermarché. Mais petit à
                petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais
                remplacer les produits
                aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même
                prix !"</p>
            <img src="{% static 'img/colette-tatou-full.png' %}" alt="Portrait Colette">
        </div>
        <div class="text-about">
            <p><u>Remy :</u> "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader,
                surtout dans les caves et
                les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les
                ingrédients de tous
                les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par
                un aliment plus sain,
                je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
            <img src="{% static 'img/ratatouille.png' %}" alt="Portrait Remy">
        </div>
    </div>
</section>
<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Contact</h2>
                <hr class="divider my-4" />
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                <div>+33 0 00 00 00 00</div>
            </div>
            <div class="col-lg-4 mr-auto text-center">
                <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                <a class="d-block" href="mailto:This website is for training purpose, no contact function.">contact@purbeurre.kp</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/main/product_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
<div class="page-section body">
    <div class="header">
        <img src="{{ product.image_url }}">
    </div>
    <br>
    <div class="title">
        <h1>{{ product.name.title }}</h1>
        <br>
        <img src="{% static 'img/' %}nutri_{{ product.nutriscore }}.png">
    </div>
    <br>
    <div class="infos">
        <div class="details">
            <p>{{ product.description }}</p>
        </div>
        <div class="details">
            <p>Repères nutritionnels pour 100g:</p>
            <ul>
                <li>Sel: {{product.salt}}</li>
                <li>Sucres: {{product.sugars}}</li>
                <li>Acides gras saturés: {{product.saturated}}</li>
                <li>Matières grasses: {{product.fat}}</li>
            </ul>
        </div>
    </div>
    <div class="details">
        <p>Le produit est disponible dans les magasins suivants:</p>
        <ul>
            {% for store in product_stores %}
            <li>
                {{store}}
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="link">
        <br>
        <a href="{{ product.url }}"><h4>Voir la fiche d'OpenFoodFacts</h4></a>
    </div>
</div>

{% endblock %}

templates/main/results.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/style_results.css' %}">
<input type="hidden" id="user_id" value="{{user.id}}">
<div class="result bd-highlight" id="{{product.id}}">
        {% if product %}
            <div class="d-flex bd-highlight justify-content-center">
                <img src="{{ product.image_url }}" />
            </div>
            <div class="d-flex bd-highlight justify-content-center">
                <a href="{% url 'product_detail' pk=product.id %}"><h2>{{ product.name.title }}</h2></a>
            </div>
            <div class="d-flex bd-highlight justify-content-center">
                 <img src="{% static 'img/' %}nutri_{{ product.nutriscore }}.png">
            </div>
        {% else %}
            <div class="d-flex bd-highlight justify-content-center">
                <p>Pas de produit à afficher</p>
            </div>
        {% endif %}
</div>
{% if suggestions and suggestions != 0 %}
<div class="suggestions">
            {% for suggestion in suggestions %}
                <div class="mx-5 mb-5 p-3 suggestion" id="suggestion_{{suggestion.id}}">
                    <a href="{% url 'product_detail' pk=suggestion.id %}">
                        <img src="{{suggestion.small_image_url}}"/>
                        <p class="p-2">{{ suggestion.name.title }}</p>
                        <img src="{% static 'img/' %}nutri_{{ suggestion.nutriscore }}.png">
                    </a>
                    {% if suggestion.id not in user_favs %}
                        <button type='submit' class='mx-5 mb-5 p-3 save_button' id="{{suggestion.id}}" data-url="{% url 'bookmark:add-bookmark' %}">
                            Sauvegarder
                            {% csrf_token %}
                        </button>
                    {% else %}
                        <p>Produit déjà dans vos favoris</p>
                    {% endif %}
                </div>
            {% endfor %}
</div>            
{% elif suggestions == 0 %}
<div class="section">
            <div class="d-flex justify-content-center">
                <p>Je ne trouve pas d'aliment plus sain dans la même catégorie...</p>
            </div>
{% endif %}
</div>

{% endblock %}

{% block scripts %}
{{ block.super }}
{% endblock %}