application/authentication/urls.py
from collections import namedtuple
from django.conf.urls import url
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views, forms

app_name = 'authentication'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html',
                                                authentication_form=forms.CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='authentication/logout.html'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('account/', views.ConsultAccountView.as_view(), name='account'),
    path('register/confirmation', views.ConfirmationView.as_view(), name='confirmation'),
    path('register/validation/<str:uid>/<str:utoken>', views.ValidationView.as_view(), name='validation'),
    path('register/success', views.SuccessView.as_view(), name='success'),
    path('account/change-password', auth_views.PasswordChangeView.as_view(template_name='authentication/change-password.html',
                                                                          success_url='password-changed'), name='change-password'),
    path('account/password-changed', auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password-changed.html'), name='password-changed'),
    path('login/reset', auth_views.PasswordResetView.as_view(template_name='authentication/password_reset_1.html',
                                                             email_template_name='authentication/password_reset_email.html',
                                                             subject_template_name='authentication/password_reset_subject.txt',
                                                             success_url='reset_confirmed'), name='forgotten-password'),
    path('login/reset_confirmed', auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_2.html'), name='reset_confirmed'),
    path('login/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_3.html',
                                                                                     success_url=reverse_lazy('authentication:password_reset_complete')), name='password_reset_confirm'),
    path('login/reset/confirmed', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_4.html'), name='password_reset_complete'),
]

pur_beurre/urls.py
from django.contrib import admin
from django.conf.urls import handler404, url
from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('application.main.urls'), name="home"),
    url('admin/', admin.site.urls),
    url('user/', include('application.authentication.urls'), name="user"),
    url('bookmark/', include('application.bookmark.urls'), name='bookmarks'),
]

handler404 = 'pur_beurre.views.handler404_view'

application/authentication/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models


class User(AbstractUser):
    """
    Custom model class of User.
    """
    username = models.CharField(default='', max_length=20)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    registration_token = models.CharField(default='', max_length=200)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = UserManager()

    def __str__(self) -> str:
        return self.first_name + ' ' + self.last_name + ' ' + self.email

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_email(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

application/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, label="Prénom")
    last_name = forms.CharField(max_length=50, label="Nom de famille")

    class Meta():
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        exclude = []


class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login': _(
            "Veuillez renseigner une adresse email et un mot de passe valides. Remarquez que chacun de ces champs est sensible à la casse (différenciation des majuscules/minuscules)."
        ),
        'inactive': ("Veuillez valider votre compte en cliquant sur le lien reçu par courriel pour vous connecter."),
    }

application/authentication/views.py
from application.bookmark.views import User
from django.http.response import HttpResponse
from pur_beurre.settings.base import EMAIL_HOST_USER
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.exceptions import ObjectDoesNotExist
from .forms import RegisterForm


class RegisterView(FormView):
    """
    View managing the registration of a user.
    """
    template_name = 'authentication/register.html'  # comme un get() integré
    form_class = RegisterForm  # notre formulaire
    success_url = 'confirmation'  # url de notre page de success
    activation_token = PasswordResetTokenGenerator()

    def form_valid(self, form: form_class):
        """
        Function called when the form is filled up and the button clicked.
        It only comes if the data in the form are valid.
        """
        form.save()
        new_user_email = form['email'].value()
        link = RegisterView.generating_link(self, new_user_email)
        RegisterView.sending_email(self, link, new_user_email)
        return super().form_valid(form)

    def generating_link(self, email):
        """
        Function called during the process of validating the form.
        It's going to use the email address given by the user in the form and prepare the link in the email. 
        """
        new_user = User.objects.get(email=email)
        generated_token = self.activation_token.make_token(new_user)
        new_user.registration_token = generated_token
        new_user.save()
        encoded_token = urlsafe_base64_encode(force_bytes(generated_token))
        current_domain = self.request.get_host()
        current_url = self.request.get_full_path()
        link = 'http://' + str(current_domain + current_url) + 'validation/'\
               + urlsafe_base64_encode(force_bytes(email)) + '/' + encoded_token
        return link

    def sending_email(self, link, email):
        """
        Function called once the link is generated.
        It sends the activation email to the new user.
        """
        send_mail(
            "Lien d'activation de votre compte PurBeurre.",
            "Cliquez sur le lien d'activation pour valider votre compte: \n" + link + ".\n\nL'équipe PurBeurre.",
            EMAIL_HOST_USER,
            [email],
            fail_silently=False)


class ConfirmationView(TemplateView):
    template_name = 'authentication/confirmation.html'


class ValidationView(FormView):
    """
    View managing the step when the user has to confirm his registration through his emails.
    """
    template_name = 'authentication/confirmation.html'  # template de validation de l'enregistrement.
    success_url = 'success'

    def get(self, request, uid, utoken):
        try:
            email_to_find = force_text(urlsafe_base64_decode(uid))
            token_to_find = force_text(urlsafe_base64_decode(utoken))
            user = User.objects.get(email=email_to_find, registration_token=token_to_find)
            user.is_active = True
            user.save()
            return redirect('authentication:success')
        except(User.DoesNotExist, TypeError, ValueError):
            return render(request, template_name='page_not_found.html')


class SuccessView(TemplateView):
    """
    Template displayed when registered.
    """
    template_name = 'authentication/registered.html'


class ConsultAccountView(TemplateView):
    """
    View called when consulting the user account.
    """
    template_name = 'authentication/account.html'

    def get(self, request):
        return render(request, self.template_name, locals())

templates/authentication/account.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/account.css' %}">
{% if user.is_authenticated %}
    <div class="head">
        <div class="d-flex justify-content-center">
            <h2>Bonjour  {{ user.first_name }} !</h2>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="d-flex flex-column justify-content-center">
            <p>Email: {{user.email}}</p>
        </div>
    </div>
    <br>
    <div class="d-flex justify-content-center">
        <div class="d-flex flex-column justify-content-center">
            <a href="{% url 'authentication:change-password' %}">
                Modifier mon mot de passe
            </a>
        </div>
    </div>
{% else %}
    <div class="head">
        <div class="d-flex justify-content-center">
            <h2>Connectez-vous pour accéder au détail de votre compte.</h2>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/authentication/change-password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block top_menu %}
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
    {% if user.is_authenticated %}
    <h2 class="text-center">Modification du mot de passe</h2>
    <div class="text-center mb-100">
        <form action="{% url 'authentication:change-password' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button id="confirmer" type="submit" class="btn btn-pastel-teal connect">Valider</button>
        </form>
    </div>
    {% else %}
        <h3>Connectez-vous pour modifier votre mot de passe</h3>
    {% endif %}
</div>
{% endblock %}

templates/authentication/confirmation.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
    <div class="d-flex justify-content-center">
        <h2>Validation d'inscription en cours</h2>
    </div>
    <div class="d-flex justify-content-center">
        <p>Vérifiez vos courriels et cliquez sur le lien d'activation du compte</p>
    </div>
</div>
{% endblock %}

templates/authentication/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block top_menu %}
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
    {% if user.is_authenticated %}
    <h2 class="text-center">Vous êtes déjà connecté</h2>
    {% else %}
    <h2 class="text-center">Connexion</h2>
    <div class="text-center mb-100">
        <form action="{% url 'authentication:login' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button id="confirmer" type="submit" class="btn btn-pastel-teal connect">Se connecter</button>
        </form>
        <br>
        <a id="register" href="{% url 'authentication:register' %}">Pas encore de compte ? Inscrivez-vous ici.</a>
        <br>
        <br>
        <a id="reset_password" href="{% url 'authentication:forgotten-password' %}">Mot de passe oublié.</a>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/authentication/logout.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="page-section">
    <br>
    <br>
    <div class="d-flex justify-content-center">
        <h3>Vous êtes déconnecté.</h3>
    </div>
    
</div>
{% endblock %}

templates/authentication/password-changed.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block top_menu %}
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
    {% if user.is_authenticated %}
    <h2 class="text-center">Mot de passe modifié</h2>
    {% else %}
        <h3>Connectez-vous pour modifier votre mot de passe</h3>
    {% endif %}
</div>
{% endblock %}

templates/authentication/password_reset_1.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block top_menu %}
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
    {% if user.is_authenticated %}
        <h2 class="text-center">Vous êtes déjà connecté</h2>
        <br>
        <div class="text-center mb-100">
            <a id="register" href="{% url 'authentication:change-password' %}">Cliquez ici pour modifier votre mot de passe ici.</a>
        </div>
    {% else %}
        <h2 class="text-center">Mot de passe oublié</h2>
        <div class="text-center mb-100">
            <br>
            <p>Entrez votre adresse email pour recevoir un lien de réinitialisation du mot de passe.</p>
            <br>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button id="confirmer" type="submit" class="btn btn-pastel-teal connect">Valider</button>
            </form>
        </div>
    {% endif %}
</div>
{% endblock %}

templates/authentication/password_reset_2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block top_menu %}
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
    {% if user.is_authenticated %}
        <h2 class="text-center">Vous êtes déjà connecté</h2>
        <br>
        <div class="text-center mb-100">
            <a id="register" href="{% url 'authentication:change-password' %}">Cliquez ici pour modifier votre mot de passe ici.</a>
        </div>
    {% else %}
        <h2 class="text-center">Mot de passe oublié</h2>
        <div class="text-center mb-100">
            <p>Un lien d'activation vient d'être envoyé à l'adresse demandée</p>
        </div>
    {% endif %}
</div>
{% endblock %}

templates/authentication/password_reset_3.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block top_menu %}
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
        <h2 class="text-center">Mot de passe oublié</h2>
        <div class="text-center mb-100">
            <p>Indiquez un nouveau mot de passe</p>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button id="confirmer" type="submit" class="btn btn-pastel-teal connect">Valider</button>
            </form>
            <br>
            <p>Si l'espace prévu pour indiquer un nouveau mot de passe ne s'affiche plus, recommencer l'opération depuis la page 'Me connecter'.</p>
        </div>
</div>
{% endblock %}

templates/authentication/password_reset_4.html
{% extends 'base.html' %}
{% block top_menu %}
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
  <br>
  <p class="text-center">
    Votre mot de passe a bien été modifié. Vous pouvez vous <a href="{% url 'authentication:login' %}" style="font-style: italic; text-decoration: underline;">connecter ici</a> .
  </p>
</div>
{% endblock %}

templates/authentication/password_reset_email.html
{% autoescape off %}
Une demande de réinitialisation du mot de passe a été demandée pour le compte associé à l'adresse email: {{ email }}.
Pour le modifier, cliquez sur le lien ci-dessous:
{{ protocol}}://{{ domain }}{% url 'authentication:password_reset_confirm' uidb64=uid token=token %}

L'équipe PurBeurre
{% endautoescape %}

templates/authentication/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block top_menu %}
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<div class="page-section">
    <div class="p-5">
        <h2>Inscription</h2>
        <div class="mb-100">
            <form action="{% url 'authentication:register' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button type="submit" class="btn btn-pastel-teal connect">S'inscrire</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/authentication/registered.html
{% extends 'base.html' %}
{% block content %}
<div class="page-section">
    <div class="d-flex justify-content-center">
        <h2>{{ user.username }}Vous êtes maintenant enregistré, bienvenue !</h2>
    </div>
</div>
{% endblock %}