application/authentication/urls.py
from collections import namedtuple
from django.conf.urls import url
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views, forms

app_name = 'authentication'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html',
                                                authentication_form=forms.CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='authentication/logout.html'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('account/', views.ConsultAccountView.as_view(), name='account'),
    path('register/confirmation', views.ConfirmationView.as_view(), name='confirmation'),
    path('register/validation/<str:uid>/<str:utoken>', views.ValidationView.as_view(), name='validation'),
    path('register/success', views.SuccessView.as_view(), name='success'),
    path('account/change-password', auth_views.PasswordChangeView.as_view(template_name='authentication/change-password.html',
                                                                          success_url='password-changed'), name='change-password'),
    path('account/password-changed', auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password-changed.html'), name='password-changed'),
    path('login/reset', auth_views.PasswordResetView.as_view(template_name='authentication/password_reset_1.html',
                                                             email_template_name='authentication/password_reset_email.html',
                                                             subject_template_name='authentication/password_reset_subject.txt',
                                                             success_url='reset_confirmed'), name='forgotten-password'),
    path('login/reset_confirmed', auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_2.html'), name='reset_confirmed'),
    path('login/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_3.html',
                                                                                     success_url=reverse_lazy('authentication:password_reset_complete')), name='password_reset_confirm'),
    path('login/reset/confirmed', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_4.html'), name='password_reset_complete'),
]

application/bookmark/urls.py
from django.urls import path
from . import views

app_name = 'bookmark'

urlpatterns = [
    path('consult/', views.BookmarksView.as_view(), name='consult'),
    path('add/', views.AddBookmarkView.as_view(), name='add-bookmark'),
    # path('check/', views.CheckBookmarkView.as_view(), name='check-bookmark'),
]

pur_beurre/urls.py
from django.contrib import admin
from django.conf.urls import handler404, url
from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('application.main.urls'), name="home"),
    url('admin/', admin.site.urls),
    url('user/', include('application.authentication.urls'), name="user"),
    url('bookmark/', include('application.bookmark.urls'), name='bookmarks'),
]

handler404 = 'pur_beurre.views.handler404_view'

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pur Beurre</title>
        <!-- Favicon-->
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'img/logo_pur_beurre-favicon.png' %}" class="icon" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <div id="page">
            <!-- Header-->
        <div id="header">
            <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <a class="navbar-brand js-scroll-trigger" href="{% url 'home' %}">
                            <img class="logo" src="{% static 'img/logo_pur_beurre.png' %}" alt=""> Pur Beurre
                        </a>
                        {% if user.is_authenticated %}
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <form method="get" action="/results/" style="float: right;">
                                    <input class="form-control" type="text" placeholder="Chercher un produit" name="recherche" required>
                                </form>
                            </li>
                        </ul>
                        {% endif %}
                        <ul class="navbar-nav ml-auto liste">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a id="personal account" class="nav-link js-scroll-trigger" href="{% url 'authentication:account' %}"
                                    title="mon compte">
                                    <i class="fa fa-user fa-2x icon"></i>
                                </a>
                            </li>
                            <li class="nav-item ml-4">
                                <a id="bookmarks" class="nav-link js-scroll-trigger" href="{% url 'bookmark:consult' %}"
                                    title="mes favoris">
                                    <img src="{% static 'img/bookmarks.png' %}" alt="" class="icon-carrot">
                                </a>
                            </li>
                            <li class="nav-item ml-4 mr-4">
                                <a id="log out" class="nav-link js-scroll-trigger" href="{% url 'authentication:logout' %}"
                                    title="me déconnecter">
                                    <i class="fa fa-sign-out-alt fa-2x icon"></i>
                                </a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a id="log in" class="nav-link js-scroll-trigger" href="{% url 'authentication:login' %}">
                                    Me connecter
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
            </nav>
        </div>
            <!-- Content-->
            <div>
                {% block content %}{% endblock %}
            </div>
            <!-- Footer-->
            <div id="footer">
                <footer class="bg-light py-2 fixed-bottom" id="footer">
                    <div class='container-fluid'>
                        <div class="row">
                            <div class="col-md-4"><a href="{% url 'mentions' %}">Mentions légales</a></div>
                            <div class="col-md-4">Copyright © 2021 - Victor SIMON</div>
                            <div class="col-md-4"><a href="{% url 'home' %}#contact">Contact</a></div>
                        </div>
                    </div>
                </footer>
            </div>
            <!-- Bootstrap core JS-->
            <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Third party plugin JS-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
            <!-- Core theme JS-->
            <script src="{% static 'js/scripts.js' %}"></script>
            {% block scripts %}
            {% endblock %}
        </div>
    </body>
</html>

templates/mentions.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/mentions.css' %}">
<div class="section">
    <div class="d-flex mt-5 justify-content-center">
        <h2>Mentions légales</h2>
    </div>
    <div class="mentions">
        <p>Les images et illustrations utilisées sur ce site proviennent de différentes sources.</p>
        <br>
        <p><u>Image de fond page d'accueil</u> : <a href="https://unsplash.com/photos/k60JspcBwKE"> Obtenue sur Unsplash, réalisée par Kawin Harasai</a></p>
        <p><u>Images des personnages Colette et Remy</u> : Personnages issus du <a href="https://fr.wikipedia.org/wiki/Ratatouille_(film)">film Disney "Ratatouille"</a>.</p>
        <p>Les icônes dans la barre de navigation sont les suivantes: </p>
        <ul>
            <li>
                <a href="https://fontawesome.com/icons/user">Icône "Espace personnel"</a>
            </li>
            <li>
                <a href="https://thenounproject.com/term/carrot/29691/">Icône "Mes favoris"</a>
            </li>
            <li>
                <a href="https://fontawesome.com/icons/sign-out-alt">Icône "Me déconnecter"</a>
            </li>
        </ul>
        <br>
        <p>Toutes les photos de produits sont téléchargées directement sur <a href="https://fr.openfoodfacts.org/">le site OpenFoodFacts</a>.</p>
        <p>De même que toutes les informations affichées concernant les produits que vous pourrez consulter sur notre site.</p>
        <br>
        <p>Le design est basé sur le template <a href="https://startbootstrap.com/theme/creative">Creative</a>.</p>
        <br>
        <p>Ce site est réalisé dans le cadre de la formation "Développeur d'application Python" dispensée par <a href="https://openclassrooms.com/fr/">OpenClassRooms</a>.</p>
        <br>
        <br>
        <p>Le site est hébergé via <a href="https://www.heroku.com/">Heroku</a>.</p>
    </div>
</div>
{% endblock %}

templates/page_not_found.html
{% extends 'base.html' %}
{% block content %}
<div class="page-section">
    <div class="d-flex justify-content-center">
        <h4>La page que vous recherchez n'existe pas.</h4>
    </div>
</div>
{% endblock %}